FROM golang:1.23.5

WORKDIR /app

COPY ./study_service/go.mod .
COPY ./study_service/go.sum .
RUN go mod download

COPY ./study_service/internal/dal/migrations .

RUN go build -o ./init ./init.go

CMD ["./init"]